function [filter_mask, eventBuffer, n_passed, n_total] = ...
    motionConsistencyFilter(sorted_x, sorted_y, sorted_t, ...
    imgSz, eventBuffer, mcf_params)
% MOTIONCONSISTENCYFILTER  Optical-flow plane-fitting noise filter.
%
%   Software implementation of the motion consistency noise
%   cancellation described in:
%
%       Y. Wang, B. Du, Y. Shen, K. Wu, G. Zhao, J. Sun, and
%       H. Wen, "EV-Gait: Event-based Robust Gait Recognition
%       using Dynamic Vision Sensors," Proc. IEEE/CVF CVPR,
%       pp. 6351–6360, 2019, §3.2.
%
%   PRINCIPLE:
%   Events generated by genuine object motion should form locally
%   consistent moving planes in the (x, y, t) spatio-temporal
%   volume. For each event e_i, the algorithm collects its
%   neighbours within a 3×3 spatial window and a temporal window
%   [t_i − Δt, t_i + Δt]. A plane Π = (a, b, c, d) is fitted to
%   these neighbours via least squares (SVD null-space). The local
%   optical flow velocity is then:
%
%       v = [v_x; v_y] = −ĉ · [1/â; 1/b̂]           (Eq. 4)
%
%   An event is accepted if 0 < |v| < V_max, indicating genuine
%   motion within a physically plausible speed range. Noise events
%   lack spatiotemporal coherence and fail this test.
%
%   ADAPTATION TO FRAME-BASED PROCESSING:
%   The IEI-ATS pipeline delivers events in per-frame batches,
%   sorted by linear pixel index. This filter re-sorts events
%   into temporal order (as done by the BAF and STC filters).
%   To maintain temporal continuity across frame boundaries,
%   a buffer of recent events from the previous frame (those
%   within Δt of the frame boundary) is prepended to the current
%   frame's events. These buffered events participate as
%   neighbours but are not themselves re-evaluated.
%
%   COMPARISON WITH OTHER FILTERS:
%   - BAF (Delbruck 2008): Checks for *any* neighbour activity
%     within T. No directional or velocity constraint.
%   - STC (Liu et al. 2015): Checks inter-spike interval at a
%     subsampled cell. No multi-event plane fitting.
%   - EDF (Feng et al. 2020): Density-based, counts events in
%     a local window. No velocity estimation.
%   - STCC (Li et al. 2024): Gaussian-weighted spatiotemporal
%     proximity + polarity consistency. No explicit flow.
%   - This filter (Wang et al. 2019): Fits a local plane and
%     validates the resulting optical flow velocity, making it
%     inherently directional. Most effective when object motion
%     produces coherent moving edges.
%
%   Inputs:
%     sorted_x     - [N x 1] Row coordinates of events in current
%                    frame, sorted by linear pixel index.
%     sorted_y     - [N x 1] Column coordinates of events.
%     sorted_t     - [N x 1] Timestamps [s] (absolute).
%     imgSz        - [1 x 2] Sensor dimensions [nRows, nCols].
%     eventBuffer  - Struct with fields:
%       .x         - [M x 1] Row coordinates of buffered events
%                    from the tail of the previous frame.
%       .y         - [M x 1] Column coordinates.
%       .t         - [M x 1] Timestamps [s].
%                    Initialize with empty vectors on first call:
%                      eventBuffer.x = []; eventBuffer.y = [];
%                      eventBuffer.t = [];
%     mcf_params   - Struct with fields:
%       .delta_t   - Temporal half-window [s] for neighbour search.
%                    (Paper uses 1e-3, i.e. 1 ms.)
%       .V_max     - Maximum acceptable velocity magnitude [px/s].
%                    Events with |v| > V_max are rejected.
%                    Typical values: 1e3 to 1e6 (scene-dependent).
%       .min_neighbours - Minimum number of neighbours (including
%                    the event itself) required for plane fitting.
%                    Must be >= 3 (3 points define a plane).
%                    Default: 3 (matching paper's 3×3 window).
%
%   Outputs:
%     filter_mask  - [imgSz] Binary mask at full pixel resolution.
%                    1 = at least one event passed at this pixel.
%     eventBuffer  - Updated buffer struct containing tail events
%                    from the current frame (within Δt of frame end).
%     n_passed     - Scalar. Number of events that passed.
%     n_total      - Scalar. Total number of events in this frame.
%
%   Notes:
%     - Plane fitting uses SVD. When the neighbour set is
%       degenerate (fewer than min_neighbours, or all neighbours
%       are colinear/coplanar with rank < 3), the event is
%       conservatively rejected.
%     - If â ≈ 0 or b̂ ≈ 0 the velocity component diverges.
%       Events with |â| < eps or |b̂| < eps are rejected to
%       avoid numerical instability.
%     - The 3×3 spatial neighbourhood is fixed per the paper.
%       The temporal window Δt is the primary tuning knob.
%     - Performance: O(N) per frame with a per-event SVD on a
%       small matrix (typically 5–20 rows). The spatial lookup
%       uses a grid-based hash (cell array indexed by pixel)
%       for O(1) amortised neighbour retrieval.
%
%   Example:
%     % Initialize before frame loop
%     mcf_params.delta_t = 1e-3;         % 1 ms (paper default)
%     mcf_params.V_max   = 1e5;          % px/s upper bound
%     mcf_params.min_neighbours = 3;
%     mcf_eventBuffer.x = [];
%     mcf_eventBuffer.y = [];
%     mcf_eventBuffer.t = [];
%
%     % Inside frame loop (after pixel-sorting)
%     [filter_mask, mcf_eventBuffer, n_pass, n_tot] = ...
%         filters.motionConsistencyFilter(sorted_x, sorted_y, ...
%         sorted_t, imgSz, mcf_eventBuffer, mcf_params);
%
%   References:
%     [1] Y. Wang, B. Du, Y. Shen, K. Wu, G. Zhao, J. Sun,
%         and H. Wen, "EV-Gait: Event-based Robust Gait
%         Recognition using Dynamic Vision Sensors," Proc.
%         IEEE/CVF CVPR, pp. 6351–6360, 2019.
%
%   See also: filters.backgroundActivityFilter,
%             filters.spatiotemporalCorrelation,
%             filters.stccFilter

    % ================================================================
    % 0. Parse parameters
    % ================================================================
    delta_t = mcf_params.delta_t;
    V_max   = mcf_params.V_max;

    if isfield(mcf_params, 'min_neighbours')
        min_neighbours = mcf_params.min_neighbours;
    else
        min_neighbours = 3;
    end

    nRows   = imgSz(1);
    nCols   = imgSz(2);
    n_total = length(sorted_x);

    % Numerical guard for velocity computation (avoid division by ~0)
    eps_plane = 1e-12;

    % ================================================================
    % 1. Re-sort events into temporal order
    % ================================================================
    % Input events are sorted by linear pixel index (IEI-ATS
    % convention). The motion consistency check requires causal
    % temporal processing and bidirectional temporal windowing.
    [temporal_t, time_order] = sort(sorted_t, 'ascend');
    temporal_x = sorted_x(time_order);
    temporal_y = sorted_y(time_order);

    % ================================================================
    % 2. Prepend buffered events from previous frame
    % ================================================================
    % Buffered events participate as potential neighbours for events
    % near the start of the current frame, but are not themselves
    % re-evaluated (they were already classified in their frame).
    n_buf = length(eventBuffer.t);

    if n_buf > 0
        all_x = [eventBuffer.x(:); temporal_x];
        all_y = [eventBuffer.y(:); temporal_y];
        all_t = [eventBuffer.t(:); temporal_t];
    else
        all_x = temporal_x;
        all_y = temporal_y;
        all_t = temporal_t;
    end

    n_all = length(all_t);

    % ================================================================
    % 3. Build spatial lookup grid
    % ================================================================
    % For each pixel (r, c), store a list of indices into the
    % all_x/all_y/all_t arrays. This enables O(1) retrieval of
    % events at any pixel within the 3×3 neighbourhood.
    %
    % Using a cell array of size [nRows, nCols]. For sparse event
    % data (typical <5% fill), this is memory-efficient — most
    % cells remain empty.
    pixelLists = cell(nRows, nCols);

    for k = 1:n_all
        r = all_x(k);
        c = all_y(k);
        pixelLists{r, c} = [pixelLists{r, c}; k];
    end

    % ================================================================
    % 4. Per-event plane fitting and velocity check
    % ================================================================
    pass_flag = false(n_total, 1);
    n_passed  = 0;

    % 8-connected neighbourhood offsets (including self: dr=0, dc=0)
    dr = [-1 -1 -1  0  0  0  1  1  1];
    dc = [-1  0  1 -1  0  1 -1  0  1];

    for i = 1:n_total
        % Map back to the all_* index space (offset by n_buf)
        idx_all = i + n_buf;

        ex = all_x(idx_all);
        ey = all_y(idx_all);
        et = all_t(idx_all);

        % ---------------------------------------------------------
        % Collect spatiotemporal neighbours (3×3 × [t−Δt, t+Δt])
        % ---------------------------------------------------------
        neighbour_idx = [];

        for k = 1:9
            nr = ex + dr(k);
            nc = ey + dc(k);

            % Boundary check
            if nr < 1 || nr > nRows || nc < 1 || nc > nCols
                continue;
            end

            cell_events = pixelLists{nr, nc};
            if isempty(cell_events)
                continue;
            end

            % Temporal window filter
            t_neighbours = all_t(cell_events);
            in_window = abs(t_neighbours - et) <= delta_t;

            neighbour_idx = [neighbour_idx; cell_events(in_window)]; %#ok<AGROW>
        end

        % ---------------------------------------------------------
        % Plane fitting (Eq. 3 in paper)
        % ---------------------------------------------------------
        n_neighbours = length(neighbour_idx);

        if n_neighbours < min_neighbours
            % Not enough support — reject
            continue;
        end

        % Build data matrix A = [x_j, y_j, t_j, 1]
        A = [double(all_x(neighbour_idx)), ...
             double(all_y(neighbour_idx)), ...
             all_t(neighbour_idx), ...
             ones(n_neighbours, 1)];

        % SVD: the plane normal is the right singular vector
        % corresponding to the smallest singular value
        [~, S_mat, V_mat] = svd(A, 'econ');

        % Check rank: if the 3rd singular value is ~0, the
        % points are effectively colinear — plane is undefined
        svals = diag(S_mat);
        if length(svals) < 4 || svals(end) < eps_plane
            % Degenerate configuration — reject
            continue;
        end

        % Plane coefficients: Π = (a, b, c, d)
        plane = V_mat(:, end);
        a_hat = plane(1);
        b_hat = plane(2);
        c_hat = plane(3);
        % d_hat = plane(4);  % Not used for velocity

        % ---------------------------------------------------------
        % Velocity computation (Eq. 4 in paper)
        % ---------------------------------------------------------
        if abs(a_hat) < eps_plane || abs(b_hat) < eps_plane
            % Velocity diverges — reject
            continue;
        end

        vx = -c_hat / a_hat;
        vy = -c_hat / b_hat;
        v_mag = sqrt(vx^2 + vy^2);

        % ---------------------------------------------------------
        % Motion consistency check
        % ---------------------------------------------------------
        % Accept if the event is genuinely moving (v > 0) and
        % within a physically plausible range (v < V_max).
        if v_mag > 0 && v_mag < V_max
            pass_flag(i) = true;
            n_passed = n_passed + 1;
        end
    end

    % ================================================================
    % 5. Build per-pixel binary mask
    % ================================================================
    filter_mask = zeros(imgSz);

    passed_x = temporal_x(pass_flag);
    passed_y = temporal_y(pass_flag);

    if ~isempty(passed_x)
        passed_lin = sub2ind(imgSz, passed_x, passed_y);
        filter_mask(passed_lin) = 1;
    end

    % ================================================================
    % 6. Update event buffer for next frame
    % ================================================================
    % Retain events from the tail of the current frame that fall
    % within Δt of the frame's last timestamp. These serve as
    % neighbours for events at the start of the next frame.
    if n_total > 0
        t_end = temporal_t(end);
        tail_mask = (temporal_t >= t_end - delta_t);

        eventBuffer.x = temporal_x(tail_mask);
        eventBuffer.y = temporal_y(tail_mask);
        eventBuffer.t = temporal_t(tail_mask);
    else
        eventBuffer.x = [];
        eventBuffer.y = [];
        eventBuffer.t = [];
    end

end